name: Release Version

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout APIs repo (source)
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.25.x

      - name: Generate Protobuf via Makefile
        run: make all

      # Download go-genproto repo
      - name: Checkout go-genproto
        uses: actions/checkout@v4
        with:
          repository: smallbiznis/go-genproto
          token: ${{ secrets.ACCESS_TOKEN }}
          path: gen

      # Sync generated files from API â†’ go-genproto repo
      - name: Sync generated proto output
        run: |
          rsync -av --delete ./gen/go/ gen/

      - name: Commit + Tag go-genproto
        working-directory: gen
        run: |
          git config user.email "bot@smallbiznis.io"
          git config user.name "SmallBiznis Bot"

          git add .
          git commit -m "release $GITHUB_REF_NAME" || echo "Nothing to commit"

          git tag -f $GITHUB_REF_NAME
          git push ori
